### PR TITLE
Improve tokenization performance

### PR DESCRIPTION
**Pull request by wuyongzheng**
My train.txt is about 1GB. The tokenization speed is about 1 dialogue per second. preprocess_raw_data() will take about 80 days to finish. After making the change, it's 5000 dialogue per second.

### CODE REVIEW

**Comment by yangjianxin1** [comment]
I have used the preprocess_raw_data() function to tokenize train.txt about 800M,it only took a few minutes.There are indeed problems with efficiency,thanks for your advice,I will check and update the code.

**Comment by wuyongzheng** [comment]
Is your training sample a DOS text file? I use unix text files. I guess it might because `"\r\n" in data` being slow for unix text files.

**Comment by yangjianxin1** [comment]
emm~,I have dealt with both situation separately
    if "\r\n" in data:
        train_data = data.split("\r\n\r\n")
    else:
        train_data = data.split("\n\n")

**Comment by wuyongzheng** [comment]
I'm trying to figure out why it's slow for me, but fast for you. For example, `'a' in 'aaaaaaaaaaaaaaa'` runs faster than `'b' in 'aaaaaaaaaaaaaaa'`. In my case, unix file doesn't contain '\r\n', so the whole 1GB file has to be scanned, which takes 80 days in total. In your case, only a few bytes are scanned.

**Comment by ghosthamlet** [comment]
I have the same problem. The pull request is right, if your data file is in dos format, `'\r\n' in data` will success fast when it first see '\r\n', and '\r\n' is very close to the search start position, no matter from start, middle or end of data; but if in unix format, when there is no '\r\n', `'\r\n' in data` will scan the whole huge data, it is nearly two hundred times slow down for my 273M data file, if it just run several times or data is very small, no problem, but when it run hundreds of thousands times in a loop and data is large, it sucks.  
I think this will be better: change the code `"\r\n" in dialogue` in pull request to `is_dos_file`, also replace the above `"\r\n" in data` to `is_dos_file`, and add `is_dos_file = "\r\n" in data`.

**Pull request closed without merging**
